name: Publish to PyPI

on:
  release:
    types: [published] # Se dispara cuando publicas un Release en GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi # Debe coincidir con el nombre de tu environment en Settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
